-- ==============================================================================
-- UPPERTIME - SCRIPT SQL COMPLETO PARA O SUPABASE
-- ==============================================================================
-- Como usar:
-- 1. Acesse o seu painel do Supabase (https://supabase.com/dashboard)
-- 2. Selecione o seu projeto
-- 3. No menu lateral, clique em "SQL Editor"
-- 4. Cole este script e clique em "Run" (Executar)
-- ==============================================================================

-- 1. TABELA PRINCIPAL DE PONTOS / HORÁRIOS BATIDOS
CREATE TABLE IF NOT EXISTS tabela_pontos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  data_registro DATE NOT NULL,
  horario_esperado TEXT NOT NULL,
  horario_real TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Índices para consultas ultra rápidas por usuário e data
CREATE INDEX IF NOT EXISTS idx_tabela_pontos_user_date ON tabela_pontos (user_id, data_registro);

-- Habilita segurança por linha (Row Level Security)
ALTER TABLE tabela_pontos ENABLE ROW LEVEL SECURITY;

-- Remove políticas antigas se existirem para evitar conflitos na recriação
DROP POLICY IF EXISTS "Usuários podem visualizar apenas seus próprios pontos" ON tabela_pontos;
DROP POLICY IF EXISTS "Usuários podem inserir seus próprios pontos" ON tabela_pontos;
DROP POLICY IF EXISTS "Usuários podem atualizar seus próprios pontos" ON tabela_pontos;
DROP POLICY IF EXISTS "Usuários podem deletar seus próprios pontos" ON tabela_pontos;

-- Políticas de acesso isolado por usuário
CREATE POLICY "Usuários podem visualizar apenas seus próprios pontos"
  ON tabela_pontos FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Usuários podem inserir seus próprios pontos"
  ON tabela_pontos FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Usuários podem atualizar seus próprios pontos"
  ON tabela_pontos FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Usuários podem deletar seus próprios pontos"
  ON tabela_pontos FOR DELETE
  USING (auth.uid() = user_id);


-- 2. TABELA DE CONFIGURAÇÕES INDIVIDUAIS DE HORÁRIOS POR USUÁRIO
CREATE TABLE IF NOT EXISTS configuracoes_usuario (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  config JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Habilita segurança por linha (Row Level Security)
ALTER TABLE configuracoes_usuario ENABLE ROW LEVEL SECURITY;

-- Remove políticas antigas se existirem
DROP POLICY IF EXISTS "Usuários podem visualizar suas próprias configurações" ON configuracoes_usuario;
DROP POLICY IF EXISTS "Usuários podem inserir suas próprias configurações" ON configuracoes_usuario;
DROP POLICY IF EXISTS "Usuários podem atualizar suas próprias configurações" ON configuracoes_usuario;
DROP POLICY IF EXISTS "Usuários podem deletar suas próprias configurações" ON configuracoes_usuario;

-- Políticas de acesso isolado por usuário
CREATE POLICY "Usuários podem visualizar suas próprias configurações"
  ON configuracoes_usuario FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Usuários podem inserir suas próprias configurações"
  ON configuracoes_usuario FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Usuários podem atualizar suas próprias configurações"
  ON configuracoes_usuario FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Usuários podem deletar suas próprias configurações"
  ON configuracoes_usuario FOR DELETE
  USING (auth.uid() = user_id);
